### ISSUE TITLE
Try out Lesson 00 - Setting up your Python/ArcGIS Development Environment

### ISSUE THREAD

**Issue by nygeog** [pratt-savi-810/pratt-savi-810-2018-10#1]
@SpatialUrban, can you try and set up GitHub Desktop and PyCharm on Windows on your machine? 

Check it out here:
~~https://github.com/pratt-savi-810/pratt-savi-810-2018-10/tree/master/lessons/lesson_00~~
https://github.com/pratt-savi-810/pratt-savi-810-2018-10/tree/master/lessons/lesson_00_python_setup

Report any issues in this thread. 

Note: this is public repo :)

**Comment by nygeog** [comment]
@SpatialUrban I also created a Google Calendar, as best as possible try and keep a general time of how long it took to do this and other tasks.

**Comment by SpatialUrban** [comment]
@nygeog - Will run through the lesson / setup environment this week and leave any comments / edits here.  Saw the Google Calender invite as well -

**Comment by SpatialUrban** [comment]
@nygeog - Completed Lesson 00 in about 45 minutes on 08.28.2018 (can def be completed more quickly, I wasn't giving it 100% attention).  Note I did not install optional Atom and Git components.

**Comment by nygeog** [comment]
Aight @SpatialUrban cool - thanks a lot - I'll close this out. 

If you have specific questions for what you want to know about PyCharm Open an new Issue and I'll make a lesson on PyCharm. 

Thanks.

**Comment by nygeog** [comment]
Add images @SpatialUrban added;

https://github.com/pratt-savi-810/pratt-savi-810-2018-10/commit/2d58374bc9060c6f092be1b393caee828a223292

to **lesson_00_python_setup**
