### ISSUE TITLE
census python api 

### ISSUE THREAD

**Issue by nygeog** [pratt-savi-810/pratt-savi-810-2018-10#28]
https://github.com/datamade/census

A simple wrapper for the United States Census Bureau's API.

**Comment by SpatialUrban** [comment]
Here's a brief python 3 code sample for accessing api census data and loading into a dataframe

# install required modules / dependencies @ command line first

# pip install Census
# pip install us

# acquire Census API Key

# https://api.census.gov/data/key_signup.html

# import modoles as necessary

from census import Census
import pandas as pd
from us import states

# access census data api

apikey = '070d9ec1740f58b5662d96ff3bfd4417427e8c3d'  # NOTE:  OBTAIN YOUR OWN KEY, DO NOT USE THIS KEY
c      = Census(apikey)

# import 2016 population data for NYS census tracts into data frame

# census total population variable code = B01003_001E

df = pd.DataFrame(c.acs5.state_county_tract('B01003_001E', states.NY.fips, '*', '*'))

# dataframe variable = new dataframe(access.censusdatatype.geography(census variable, state, 
#                                                                    all counties, all tracts))

df.head(10)

# total pop / county / state / census tract
