### ISSUE TITLE
ArcGIS Pro

### ISSUE THREAD

**Issue by bagtas3** [pratt-savi-810/pratt-savi-810-2018-10#31]
I'm unable to authorize my computer for ArcGIS Pro. I have a student trial license--I was able to successfully authorize my ArcGIS Desktop but it seems I can't do the same for ArcGIS Pro.

I'm actually getting the same exact message Danny got on the first day of class, so I'm wondering what you did to resolve that problem? If you need any other information just let me know

**Comment by nygeog** [comment]
@bagtas3 please contact Case about Pro issues/student accounts - he emailed the initial authorization. CC my Pratt email address. Thx.
