### ISSUE TITLE
cannot import arcpy module

### ISSUE THREAD

**Issue by hhernandez2783** [pratt-savi-810/pratt-savi-810-2018-10#32]
HI Danny and Matt,

I'm trying to run section of my code separately shown below and I get the "ImportError: No module named arcpy" error message. can you please assist? sorry I didnt quit understand how to  format the code below but my question is really just on being able to import arcpy module which I cant do right now. hope you can help. thanks. Hector

```
import arcpy

fc = "C:\Users\Hector Hernandez\Documents\GitHub\pratt-savi-810-2018-10\students\hhernandez2783\Test\shp.zip"
mxd = arcpy.mapping.MapDocument("CURRENT")
df = arcpy.mapping.ListDataFrames(mxd)[0]

arcpy.MakeFeatureLayer_management(fc, "point")
addLayer = arcpy.mapping.Layer("point")
arcpy.mapping.AddLayer(df, addLayer)
```

**Comment by nygeog** [comment]
To format code add "```" above and below your code block. 

What machine are you using? Are you using ArcMap or PyCharm? And let's check your Project interpreter in PyCharm if you're using it. Upload a screencapture or the link in PyCharm. Thx

**Comment by hhernandez2783** [comment]
Im using my own personal computer with Windows 7 professional. I'm using pycharm 2 (see details below) to run the formatted code below. I'm trying to run the code to open a shapefile. When I go to file, and then settings, it shows the  interpreter I was using was:
![image](https://user-images.githubusercontent.com/44526460/48508006-6faa6880-e81b-11e8-8e35-c9b586c35815.png)
I just changed the interpreter to the below and I'm not getting the arcpy error message, so i guess it was that???
![image](https://user-images.githubusercontent.com/44526460/48508066-97013580-e81b-11e8-8642-4b2df1ec6924.png)

PyCharm 2018.2.4 (Community Edition)
Build #PC-182.4505.26, built on September 19, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

'''import arcpy

fc = "C:\Users\Hector Hernandez\Documents\GitHub\pratt-savi-810-2018-10\students\hhernandez2783\Test\shp.zip"
mxd = arcpy.mapping.MapDocument("CURRENT")
df = arcpy.mapping.ListDataFrames(mxd)[0]

arcpy.MakeFeatureLayer_management(fc, "point")
addLayer = arcpy.mapping.Layer("point")
arcpy.mapping.AddLayer(df, addLayer)'''

**Comment by nygeog** [comment]
Boom! Nice fix! I'll close this Issue.
