### ISSUE TITLE
select attribute error

### ISSUE THREAD

**Issue by hhernandez2783** [pratt-savi-810/pratt-savi-810-2018-10#33]
Hi Danny & Matt,

Below part of my code that I want to use to select an attribute from my shapefile (Brooklyn Bridge).

'''import arcpy

arcpy.env.workspace = "C:\Users\Hector Hernandez\Documents\GitHub\pratt-savi-810-2018-10\students\hhernandez2783\Test"
arcpy.SelectLayerByAttribute_management("East_NJtoMN_NJtoSI_Brgs", "NEW_SELECTION", """ "brg" = 'Brooklyn Bridge' """)'''

I receive the following error message. Can you please let me know what I am doing wrong?
![image](https://user-images.githubusercontent.com/44526460/48514269-02530380-e82c-11e8-8d8b-50eb88f3833b.png)
 
Here is what what the map/attributes table that I am trying to select the attribute from looks like:
![image](https://user-images.githubusercontent.com/44526460/48514374-2c0c2a80-e82c-11e8-9588-31d7609b34a7.png)

Thanks,

Hector

**Comment by nygeog** [comment]
If its not already created as a layer i.e. ```arcpy.MakeFeatureLayer_management("C:/data/mexico.gdb/cities","cities_lyr")``` it's not going to know that its a layer. @hhernandez2783 can you send a link to the code in GitHub? And can see the context of if you created a layer in memory or not?
