### ISSUE TITLE
Can you see my updated project?

### ISSUE THREAD

**Issue by caitlinwunsch** [pratt-savi-810/pratt-savi-810-2018-10#39]
Hey, just wanted to make sure you can see my project on my branch. The finial version is updated but I am confirming you can see it correctly.

Thanks,
Caitlin

**Comment by nygeog** [comment]
Hey @caitlinwunsch, looks like its here: https://github.com/pratt-savi-810/pratt-savi-810-2018-10/tree/cwunsch-Project/projects/cwunsch_project

Looks fairly good w/ out testing or looking too closely. 

Make sure to grab some screenshots and screen recording in action for your docs. See Project grading: https://github.com/pratt-savi-810/pratt-savi-810-2018-10/tree/master/docs/project_grading 

Looking forward to reviewing!

**Comment by caitlinwunsch** [comment]
Hi! Ok thanks, I have a hyperlink under the project description that says “click here for video” or something like that. I couldn’t figure out how to get the video on GitHub without going through YouTube. Let me know if you can see it.

**Comment by nygeog** [comment]
Ah I see it - thanks! Also just modify the README.md to include a **Project Title**. https://github.com/pratt-savi-810/pratt-savi-810-2018-10/blob/cwunsch-Project/projects/cwunsch_project/README.md

@caitlinwunsch Looks good thus far will reply w/ review.
