### ISSUE TITLE
What can I do get three exported png files using the for loop in the code below?

### ISSUE THREAD

**Issue by hhernandez2783** [pratt-savi-810/pratt-savi-810-2018-10#40]
Hello Danny & Matt,

the code below is performing the following actions:

plotting xy coordinates from csv
creating shapefile
loading shapefile in ArcMap
labeling map features
Selecting specific map features
Zooming in on selected features
Exporting a PNG file
Repeating the last three steps for two other sets of features
the code runs with no error but I am not getting three PNG files, one for each set of features (defined as sql_1, sql_2, sql_3 in code). In stead I am getting one exported PNG file of the last set of features I want to export (sql_3)

What can I do get three exported png files using the for loop in the code below?

```
import pandas as pd
import arcpy

# Declare Variable for Location of csv File with Data
in_csv = 'C:\Users\Hector Hernandez\Documents\GitHub\pratt-savi-810-2018-10\projects\hhernandez project/brg.csv'

# Project xy Coordinates
arcpy.MakeXYEventLayer_management(
     in_csv,
     'Brg_Lng',
     'Brg_Lat',
     'in_memory_xy_layer',
 )


# Declare Variable for Output Location of Shapefile & Location of Workspace for Loading Shapefile
out_shp_worksp = 'C:\Users\Hector Hernandez\Documents\GitHub\pratt-savi-810-2018-10\projects\hhernandez project'
# Create a Shapefile
arcpy.FeatureClassToFeatureClass_conversion(
     'in_memory_xy_layer',
     out_shp_worksp,
     'brg.shp'
)


# Loading Shapefile in Map Document
# Declare Variable of Location of mxd File with Basemap for Shapefile Load
load_base = 'C:\Users\Hector Hernandez\Documents\GitHub\pratt-savi-810-2018-10\projects\hhernandez project\ld2.mxd'
# get the map document
mxd = arcpy.mapping.MapDocument(load_base)
# Set the workspace
arcpy.env.workspace = out_shp_worksp
# get the data frame
df = arcpy.mapping.ListDataFrames(mxd,"*")[0]
# Declare Variable of Location to Save Shapefile
save_ly = 'C:\Users\Hector Hernandez\Documents\GitHub\pratt-savi-810-2018-10\projects\hhernandez project/brg.shp'
# create a new layer
newlayer = arcpy.mapping.Layer(save_ly)
# add the layer to the map at the bottom of the TOC in data frame 0
arcpy.mapping.AddLayer(df, newlayer,"AUTO_ARRANGE")
# save the mxd file
mxd.save()


# Adding Labeling
layer = arcpy.mapping.ListLayers(mxd, "brg")[0] #Indexing list for 1st layer
if layer.supports("LABELCLASSES"):
    for lblclass in layer.labelClasses:
        lblclass.showClassLabels = True
layer.showLabels = True
arcpy.RefreshActiveView()
mxd.save()


sql_1 = """ "brg" = 'Brooklyn Bridge' OR "brg" = 'Manhattan Bridge' OR "brg" = 'Williamsburg Bridge' OR "brg" = 'Ed Koch Queensboro Bridge' """
sql_2 = """ "brg" = 'George Washington Bridge' OR "brg" = 'Lincoln Tunnel' OR "brg" = 'Holland Tunnel' """
sql_3 = """ "brg" = 'Bayonne Bridge' OR "brg" = 'Goethals Bridge' OR "brg" = 'Outerbridge Crossing Bridge' """

SQL_List = [sql_1, sql_2, sql_3]

for x in SQL_List:
# Select Features & Zoom
    nycbrg = arcpy.mapping.ListLayers(mxd)[0]
    arcpy.SelectLayerByAttribute_management(nycbrg, "NEW_SELECTION", x)
    df.zoomToSelectedFeatures()
    mxd.save()

# Declare Variable of Where to Save Map Export
    Make_Export = 'C:\Users\Hector Hernandez\Documents\GitHub\pratt-savi-810-2018-10\projects\hhernandez project\expmap1.png'
# Export Map
    arcpy.mapping.ExportToPNG(mxd, Make_Export, df)


```

the csv file is in a previous issue and the map document is just a map with a basemap. i can attach both here if you like. let me know.

thanks,

Hector

**Comment by nygeog** [comment]
Mostly in your last line `arcpy.mapping.ExportToPNG(mxd, Make_Export, df)` you just kept overwriting `...expmap1.png` for each view and selection.  The export needs its own image file, so use inline vars. See below:

`arcpy.mapping.ExportToPNG(mxd, '{}/{}.png'.format(map_export_dir, map_name), df)`

As mentioned in class the other day, if you want to clear the Turquoise selection color on the exported map, clear that after you zoom by adding `arcpy.SelectLayerByAttribute_management(nycbrg, "CLEAR_SELECTION", map_frame_sql)`

See the code I edited here: https://github.com/pratt-savi-810/pratt-savi-810-2018-10/tree/master/projects_scratch/hhernandez2783

I added a file called `run_bridge_export.py` which calls the `bridge_export()` function. 

Added a `config.json` so you can store your info in there and have more generic code. 

A couple other things I would modify when you submit, but otherwise looking good.

**Comment by hhernandez2783** [comment]
thanks Danny, but the link in your last email does not work? can you fix
the link?

**Comment by nygeog** [comment]
@hhernandez2783 here's the link: https://github.com/pratt-savi-810/pratt-savi-810-2018-10/tree/master/review/hhernandez2783

**Comment by hhernandez2783** [comment]
Hi Danny,

Thanks for the link. My final project with code, video and documentation is
posted under my branch at Github at the link: (
https://github.com/pratt-savi-810/pratt-savi-810-2018-10/tree/hhernandez_project/projects/hhernandez%20project
)

thanks,

Hector
