### ISSUE TITLE
Pandas issue

### ISSUE THREAD

**Issue by nygeog** [pratt-savi-810/pratt-savi-810-2018-10#42]
I'm having some trouble importing pandas and arcpy from this computer. I've tried: pip install pandas , but that hasn't worked in PyCharm.

@derekljasmin I opened a GitHub issue for this as I will not be responding to emails, only GitHub issues as mentioned.

**Comment by nygeog** [comment]
@derekljasmin you pip install from the command line. What computer are you using? I can only assist with technical/env issues for the computers at Pratt. My only advice is to make sure you are point to ArcGIS's Python in your PyCharm Interpreter. 

Here are the doc's for how to configure: 
https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html

**Comment by nygeog** [comment]
@derekljasmin can you send a screenshot of the interpreter you are using? 

Do you have ArcGIS Pro and ArcGIS Desktop 10.4 on the same machine? It's possible you haven't pip installed on both , but default both should have Pandas, you may be using a dif. Python for your system.

**Comment by derekljasmin** [comment]
![image](https://user-images.githubusercontent.com/44526687/48963994-17870b00-ef6d-11e8-9afe-46a30f9689ed.png)

See above for screenshot

**Comment by derekljasmin** [comment]
Below is what I entered into the python console and it's error responses

"C:\Users\Derek Jasmin\AppData\Local\Programs\Python\Python37-32\python.exe" "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.5\helpers\pydev\pydevconsole.py" 50153 50154
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Users\\Derek Jasmin\\Documents\\GitHub\\pratt-savi-810-2018-10\\students\\djasmin', 'C:/Users/Derek Jasmin/Documents/GitHub/pratt-savi-810-2018-10/students/djasmin'])
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 6.5.0
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)] on win32
import pip
pip install pip
  File "<ipython-input-3-8d3f3df2383c>", line 1
    pip install pip
              ^
SyntaxError: invalid syntax
import pandas
Traceback (most recent call last):
  File "C:\Users\Derek Jasmin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-38d4b0363d82>", line 1, in <module>
    import pandas
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'pandas'
import arcpy
Traceback (most recent call last):
  File "C:\Users\Derek Jasmin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-5467a3dc9fe3>", line 1, in <module>
    import arcpy
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'arcpy'
import sql
Traceback (most recent call last):
  File "C:\Users\Derek Jasmin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-885d7e1de7b2>", line 1, in <module>
    import sql
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'sql'

**Comment by nygeog** [comment]
@derekljasmin yeah that path is not ArcGIS's Python environment. 

You must have Python installed in multiple places on your machine. 

`C:/Python/ArcGIS10.6/python.exe`

or 

`C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3`

The actual path may vary depending on how its installed in your machine, but you def. need a path w/ something in an ArcGIS directory in the path.

**Comment by derekljasmin** [comment]
So I was able to switch the interpreter to C:/Python/ArcGIS10.4.1/python.exe, see below.
![image](https://user-images.githubusercontent.com/44526687/48971584-b2bdc600-efe9-11e8-95a1-bc868a4e2151.png)

However, I am still getting the same "invalid syntax" error message in the python console of PyCharm when I try "pip install pandas" or "import pandas"

**Comment by nygeog** [comment]
Hmmm. It looks like its now virtualenv b/c its your `C:/Users/.... ` path. 

It could now be that you're selecting an environment instead of the **Existing interpreter**

![image](https://user-images.githubusercontent.com/2790599/48971945-f9fa8580-efee-11e8-96fc-1f0d4be5ae1e.png)


Sorry this has required so much back and forth. I kept creating environment instead of existing interpreter on the first day of class. If you need to submit Sunday or another day or so, please shoot me an email.

**Comment by nygeog** [comment]
This is closed.
