### ISSUE TITLE
Make Feature Layer, Select Layer by Location, Feature Class to Feature Class 

### ISSUE THREAD

**Issue by nygeog** [pratt-savi-810/pratt-savi-810-2018-10#43]
* Use Make Feature Layer method (you will have to use this if performing selections via standalone script, outside of ArcGIS)
http://resources.arcgis.com/EN/HELP/MAIN/10.2/index.html#//00170000006p000000
* Use Select Layer by Location method
http://resources.arcgis.com/EN/HELP/MAIN/10.2/index.html#//001700000072000000
* Use Feature Class to Feature Class method to create new layer from selected features
http://resources.arcgis.com/EN/HELP/MAIN/10.2/index.html#//001200000020000000

```
for buffer, i in zip(list_of_buffers, len(list_of_buffers)): 
    arcpy.MakeFeatureLayer_management("C:/data/parcels.shp", "parcels_lyr_{0}".format(i))

    arcpy.SelectLayerByLocation_management(
         "parcel_lyr_{0}".format(i)", 
         "INTERSECT", 
         "c:/data.gdb/buffers_{0}.shp".format(i)
    )

    arcpy.FeatureClassToFeatureClass_conversion(
        "parcel_lyr",  # feature layer 
        "C:/output/output.gdb",   # output location
        "selected_parcels_{0}.shp".format(i),  # output name  
   )

```

https://gis.stackexchange.com/questions/171530/using-select-by-location-in-arcpy

**Comment by nygeog** [comment]
@derekljasmin also, for this submission, maybe even just getting it to work with 1 buffer to update FAR is fine, and this week we'll work on getting that function in a loop and w/ the logic of selecting the the highest FAR value.

**Comment by derekljasmin** [comment]
My code doesn't have any red or yellow errors in PyCharm, but I'm receiving some generic/basic errors when I try to run in ArcGIS. So far I've just documented the receipt of error messages instead of anything running correctly. Should I place my first submission so I can work on correcting whatever lingering errors are in the code? I've otherwise worked up to the point of intersecting a buffer file albeit a bit sloppy.

**Comment by nygeog** [comment]
Yes, @derekljasmin please submit and we'll take a look at.

**Comment by derekljasmin** [comment]
Thanks, in which folder should I submit project.py?

**Comment by nygeog** [comment]
@derekljasmin please commit it to your branch, or if you're currently working in master commit in master.

**Comment by derekljasmin** [comment]
Ok, I committed this to my branch.

**Comment by nygeog** [comment]
Thanks - closing.
