### ISSUE TITLE
AddField and CalculateField issues

### ISSUE THREAD

**Issue by adamlubitz** [pratt-savi-810/pratt-savi-810-2018-10#46]
I also might have to rework the download of multiple files since it's only working for the nybb .zip file.

Unzipping with iterating and calculating the number of days with two string fields works, but the field isn't adding and populating as it stands now.

https://github.com/pratt-savi-810/pratt-savi-810-2018-10/blob/b6e996710773f50fd1dde5ee6f876bb24be63485/projects/alubitz_project/lpc_rate.py#L57-L70

**Comment by adamlubitz** [comment]
![pycharm_screenshot](https://user-images.githubusercontent.com/7927380/48974318-ff71c300-f022-11e8-953b-32521926ece8.PNG)

I'm also working on my own pc with ArcGIS 10.3 so here's a screenshot of the interpreter.

**Comment by SpatialUrban** [comment]
Hey Adam, you can run the Add Fields and Calculate Fields outside of the for loops, those functions run on the data globally, so you don't need to iterate through each row call the function on each data field you wish to make the calculation for.  

Regarding the time calculation not population, you can subtract the start date from the end date, which will yield to the total number of days in the new field (be sure the start and end date fields are "DATE" field types, I set the new field as a Long Interger).  I ran a calculate field in ArcMap and the python snippet looks like this:

arcpy.CalculateField_management(in_table="LiquorLicenses_Point", field="TEST", expression="[License_Expiration_Date] - [License_Effective_Date]", expression_type="VB", code_block="")

Your new code should look something like this (w/o the loops):

arcpy.AddField_management(points, "rate", "LONG") .  #other field parameters can be left blank
arcpy.CalculateField_management(points, rate, "[DESDATE] - [CALDATE]", "VB")

Let me know how that works out for you - 

Matt

**Comment by nygeog** [comment]
@adamlubitz 

Closing, we're going to review all the branches, if not committed yet, we'll incorporate @SpatialUrban's commits in the code review. 

Thanks

**Comment by adamlubitz** [comment]
Ok, thanks @SpatialUrban and @nygeog. I was able to get the field issues working with this code but haven't committed yet.

# convert date field types from string to date
arcpy.AddField_management(points, "cal", "DATE")
arcpy.CalculateField_management(points, "cal", "[CALDATE]", "VB")
arcpy.AddField_management(points, "des", "DATE")
arcpy.CalculateField_management(points, "des", "[DESDATE]", "VB")

# create and populate rate field
arcpy.AddField_management(points, "rate", "LONG")
arcpy.CalculateField_management(points, "rate", "[des] - [cal]", "VB")

# spatial join the new point-based data to the building polygons
arcpy.SpatialJoin_analysis(bldgs, points, "in_memory/lpc_rate")
