### ISSUE TITLE
File recognition error 

### ISSUE THREAD

**Issue by derekljasmin** [pratt-savi-810/pratt-savi-810-2018-10#47]
While trying to run the buffer functions in python, I am receiving an error message stating it can not recognize a shapefile even though it's currently open within the ArcGIS project. See the screenshot below.

![image](https://user-images.githubusercontent.com/44526687/48984481-03a4eb80-f0ca-11e8-953e-3a8b49e25d19.png)

I checked the file path and noticed this shapefile as well as the others have a lock file. Would this possibly inhibit the file recognition? (screenshot below)

![image](https://user-images.githubusercontent.com/44526687/48984499-3818a780-f0ca-11e8-8bdc-f4c88c62aeb5.png)

**Comment by nygeog** [comment]
@derekljasmin it looks to be a file path, the path in your Layers is `G:/...` while the code path is `E:/...` Closing Issue.
