### ISSUE TITLE
Project - Documentation - Kate

### ISSUE THREAD

**Issue by nygeog** [pratt-savi-810/pratt-savi-810-2018-10#68]
@kateesutt  - I don't see a link for screen recording in your README.md https://github.com/pratt-savi-810/pratt-savi-810-2018-10/tree/master/projects/ksutton_project there is a possibility it was mixed up on the pull request. 

If you add it please comment in this Issue and Assign to me. Then I will review.

**Comment by kateesutt** [comment]
Hi Danny, I replied to the email version of this, but I'm not sure if you'll get that. Was there a particular program we were supposed to use for the screen recording? I made one just now using Flashback Express, but I'm not sure how to add it to my readme file. I only know how to upload images via imgur, and it looks like you can't upload videos to imgur on desktop. I attached the video to the email I sent. How would I add it on github? It's 20 MB and the format is a 'FlashBack Movie'.

**Comment by kateesutt** [comment]
I also have edited my code some since two Saturdays ago when I made my last commit. I didn't change anything major, just changed some file directories and made it easier for a stranger to use. Do you want me to commit the edited version of my code as well?

**Comment by nygeog** [comment]
Yes,  @kateesutt please add to master. You can upload the video to anything, dropbox, imgur, doesn't really matter. Anything is fine.

**Comment by kateesutt** [comment]
Hey Danny, Okay, happy to add my new code to the master. I still don't know how to upload a video to GitHub though. I uploaded the FlashBack Movie file to my dropbox, but I don't know how to get it from there into GitHub. Sorry, I'm new to this process so I just don't know the steps. Could you elaborate a little more or point me to an article that explains how?

**Comment by nygeog** [comment]
You should be able to share the file on Dropbox as a link. Then in markdown, link to it. 

I provide this link https://daringfireball.net/projects/markdown/ in the Project email. You can use `This is an [example link](https://commons.pratt.edu/savi/)` 

Which works like this: [example link](https://commons.pratt.edu/savi/)

**Comment by kateesutt** [comment]
Hi Danny, Thanks, I think I got it. Would you be able to tell me today if the link works for you or if I need to give you permissions from my dropbox?

**Comment by nygeog** [comment]
@kateesutt thanks, haven't watched the video but will mark as completed in the grades spreadsheet.
