### ISSUE TITLE
Project - Documentation  - Derek 

### ISSUE THREAD

**Issue by nygeog** [pratt-savi-810/pratt-savi-810-2018-10#72]
@derekljasmin  - I don't see screen recording or Python dependencies in your README.md https://github.com/pratt-savi-810/pratt-savi-810-2018-10/tree/master/projects/djasmin_project there is a possibility it was mixed up on the pull request.

If you add it please comment in this Issue and Assign to me. Then I will review.

**Comment by derekljasmin** [comment]
I only have screen recordings of failed attempts to run Python in ArcGIS; see below for a zipped file of my most recent attempt.

[CD4_Rezoning - ArcMap 11_25_2018 7_14_17 PM.zip](https://github.com/pratt-savi-810/pratt-savi-810-2018-10/files/2641625/CD4_Rezoning.-.ArcMap.11_25_2018.7_14_17.PM.zip)
