### ISSUE TITLE
Project - Code Runs - Derek

### ISSUE THREAD

**Issue by nygeog** [pratt-savi-810/pratt-savi-810-2018-10#73]
@derekljasmin Going to need the shapefiles, specifically the streets file; at the very least include a link to the exact file you used. 

If you add it please comment in this Issue and Assign to me. Then I will review.

**Comment by derekljasmin** [comment]
I apologize for the delay; I started the next class, Graphic Design, which ran both Sat & Sun.

I zipped all the street shapefiles into the folder below.
[Streets.zip](https://github.com/pratt-savi-810/pratt-savi-810-2018-10/files/2641606/Streets.zip)

Below is the shapefile for tax lots in Bushwick, zipped.
[Bushwick_TaxLots.zip](https://github.com/pratt-savi-810/pratt-savi-810-2018-10/files/2641608/Bushwick_TaxLots.zip)
