### ISSUE TITLE
Updated project documenation

### ISSUE THREAD

**Issue by bagtas3** [pratt-savi-810/pratt-savi-810-2018-10#77]
Danny & Matt,

I didn't get assigned an issue for documentation, but I did notice a lot of broken links in my README (I linked to my various .py scripts and embedded some .png screenshots for reference). I used exact URLs rather than relative references, so when my branch merged into the master, the URLs I used no longer exist.

I 'm not sure if you're done reviewing my project, but I committed some changes to update those links/relative references. You should now be able to see the screenshots and click on links to my code. Apologies for any inconvenience!

**Comment by nygeog** [comment]
Okay thanks! @bagtas3 You received full points on Documentation, the branch had everything linked fine.
