### ISSUE TITLE
Code Readability Questions

### ISSUE THREAD

**Issue by kateesutt** [pratt-savi-810/pratt-savi-810-2018-10#78]
I noticed I have some Code Readability markdowns and I had a question about that. I have already updated my code to fix the PEP-8 issues, and I'll be able to commit that tonight. It also looks like I got marked down for including file names inside functions. I don't totally understand what you mean by passing them as variables, so I was wondering if you could provide an example of the right thing to do or tell me of one instance where I'm doing the wrong thing in my code. I also use a lot of {}.format(parameter) type things in my file names and I'm wondering if that would still be possible if I passed the file as a variable instead.

**Comment by nygeog** [comment]
@kateesutt just commit the PEP-8 fixes, not many folks followed the file names outside of functions instructions so it will likely be covered in re-weighting the score - so no need to worry about that.
