### ISSUE TITLE
commit problems

### ISSUE THREAD

**Issue by csutton6** [pratt-savi-810/pratt-savi-810-2018-10#79]
Hey Danny, 
I committed my edits through the terminal, forgetting that you had merged the branches already. So my code is under my branch again. I tried to figure out how to correctly commit it to the master branch, but the more recent version of the code ended up getting overwritten by what was on the branch. So really all I can tell you is that the correct code is under my project branch again and I can't figure out how to move it to the master. Thanks and sorry

**Comment by nygeog** [comment]
Copied changes to master @kateesutt
